
package com.self.cloudserver.wsdl.webservicetest2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceTestService2", targetNamespace = "http://webservice.cloudserver.self.com", wsdlLocation = "http://127.0.0.1:8081/webservice/webservice2?wsdl")
public class WebServiceTestService2_Service
    extends Service
{

    private final static URL WEBSERVICETESTSERVICE2_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICETESTSERVICE2_EXCEPTION;
    private final static QName WEBSERVICETESTSERVICE2_QNAME = new QName("http://webservice.cloudserver.self.com", "WebServiceTestService2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8081/webservice/webservice2?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICETESTSERVICE2_WSDL_LOCATION = url;
        WEBSERVICETESTSERVICE2_EXCEPTION = e;
    }

    public WebServiceTestService2_Service() {
        super(__getWsdlLocation(), WEBSERVICETESTSERVICE2_QNAME);
    }

    public WebServiceTestService2_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICETESTSERVICE2_QNAME, features);
    }

    public WebServiceTestService2_Service(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICETESTSERVICE2_QNAME);
    }

    public WebServiceTestService2_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICETESTSERVICE2_QNAME, features);
    }

    public WebServiceTestService2_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceTestService2_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceTestService2
     */
    @WebEndpoint(name = "WebServiceTestServiceImpl2Port")
    public WebServiceTestService2 getWebServiceTestServiceImpl2Port() {
        return super.getPort(new QName("http://webservice.cloudserver.self.com", "WebServiceTestServiceImpl2Port"), WebServiceTestService2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceTestService2
     */
    @WebEndpoint(name = "WebServiceTestServiceImpl2Port")
    public WebServiceTestService2 getWebServiceTestServiceImpl2Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.cloudserver.self.com", "WebServiceTestServiceImpl2Port"), WebServiceTestService2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICETESTSERVICE2_EXCEPTION!= null) {
            throw WEBSERVICETESTSERVICE2_EXCEPTION;
        }
        return WEBSERVICETESTSERVICE2_WSDL_LOCATION;
    }

}
