
package com.self.cloudserver.wsdl.webservicetest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceTestService", targetNamespace = "http://webservice.cloudserver.self.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceTestService {


    /**
     * 
     * @param param
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testWebService", targetNamespace = "http://webservice.cloudserver.self.com/", className = "com.self.cloudserver.wsdl.webservicetest.TestWebService")
    @ResponseWrapper(localName = "testWebServiceResponse", targetNamespace = "http://webservice.cloudserver.self.com/", className = "com.self.cloudserver.wsdl.webservicetest.TestWebServiceResponse")
    public String testWebService(
        @WebParam(name = "param", targetNamespace = "")
        String param);

}
